// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildPrompt(arg1) {
  return window['go']['main']['App']['BuildPrompt'](arg1);
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function GetRoles() {
  return window['go']['main']['App']['GetRoles']();
}
