// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildPrompt(arg1) {
  return window['go']['main']['App']['BuildPrompt'](arg1);
}

export function DeletePrompt(arg1) {
  return window['go']['main']['App']['DeletePrompt'](arg1);
}

export function GetModels(arg1) {
  return window['go']['main']['App']['GetModels'](arg1);
}

export function GetPrompt(arg1) {
  return window['go']['main']['App']['GetPrompt'](arg1);
}

export function GetRoles(arg1) {
  return window['go']['main']['App']['GetRoles'](arg1);
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function ListPrompts() {
  return window['go']['main']['App']['ListPrompts']();
}

export function SavePrompt(arg1) {
  return window['go']['main']['App']['SavePrompt'](arg1);
}

export function UpdatePrompt(arg1, arg2) {
  return window['go']['main']['App']['UpdatePrompt'](arg1, arg2);
}

export function ValidateAll() {
  return window['go']['main']['App']['ValidateAll']();
}
