// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BuildPrompt(arg1:main.BuildRequestDTO):Promise<main.BuildResultDTO>;

export function GetModels():Promise<Array<main.ModelDTO>>;

export function GetRoles():Promise<Array<main.RoleDTO>>;

export function IsFirstRun():Promise<boolean>;
